#include "SensorsData.h"
#include "bulkState.h"
#include "Charger.h"

IState* bulkState::Handle(Charger& charger, SensorsData& sensor, unsigned long currentTime) 
{
      IState* newState = this;
      int floatV = charger.floatVoltageTempCorrectedRaw(sensor);
      if (sensor.PVvoltage + 0.2 < sensor.batteryV) {               // if watts input from the solar panel is less than          
          newState = charger.goOff();                              // the minimum solar watts then it is getting dark so
      }
      else if (sensor.rawBatteryV > floatV - charger.powerCompensation){
        charger.pwmController.storeMpptDuty();
        newState = charger.goFloat();              // battery float voltage go to the charger battery float state            
      }                          
      else if (charger.sol_watts < LOW_SOL_WATTS) {              // else if the solar input watts is less than low solar watts
          newState = charger.goOn();                            // it means there is not much power being generated by the solar panel
      }
      else {                                    // this is where we do the Peak Power Tracking ro Maximum Power Point algorithm
          unsigned long solarPower = (unsigned long)charger.rawCurrentIn * sensor.rawBatteryV;
          if(charger.mpptReached == 1 || charger.startTracking){
            if(currentTime - lastTrackingTime > 29900 || charger.startTracking){
               // do perturbation
              stepSize = MAX_PWM_DELTA;
              delta = charger.dirrection * stepSize;
              charger.pwmController.initIIR();
              charger.pwmController.incrementDuty(delta);
              lastTrackingTime = currentTime;
              charger.mpptReached = 0; // ! reset MPPT
              rawPowerPrev = solarPower;   
              voltageInputPrev = charger.rawSolarV;           
              charger.startTracking = false;
            }
          }else{
        /*   Serial.print("power before: "); Serial.print(rawPowerPrev); 
            Serial.print("power after: "); Serial.println(solarPower); 
            Serial.print("voltage before: "); Serial.print(voltageInputPrev); 
            Serial.print("voltage after: "); Serial.print(rawSolarV);
            Serial.print("pwm: "); Serial.print(duty); 
            Serial.print("delta: "); Serial.println(delta); */
           if(solarPower > rawPowerPrev){
                charger.pwmController.incrementDuty(delta);
                rawPowerPrev = solarPower;
           } else {
                charger.pwmController.incrementDuty(-delta);
                delta /= 2;
                if(delta == 0){                                                // MPP Reached 
                  charger.pwmController.incrementDuty(-charger.stepsDown * 4); // protection against repeated overpower events                                            
                  charger.pwmController.smoothDuty();                          // smooth duty value a bit
                  charger.Reverse();                                           // Change the direction for the next tracking.
                  charger.mpptReached = 1;                                     // indicate MPP reached
                } 
              }
          }                    
        }
        return newState;      
    }
